columns =
[ { userType: 0,
    flags: 16,
    type:
     { type: 'INT4',
       name: 'Int',
       declaration: [Function],
       writeParameterData: [Function],
       id: 56 },
    colName: 'RefID',
    collation: undefined,
    precision: undefined,
    scale: undefined,
    dataLength: undefined,
    tableName: undefined },
  { userType: 0,
    flags: 9,
    type: { type: 'INTN', name: 'IntN', dataLengthLength: 1, id: 38 },
    colName: 'HotelID',
    collation: undefined,
    precision: undefined,
    scale: undefined,
    dataLength: 4,
    tableName: undefined },
  { userType: 0,
    flags: 9,
    type:
     { type: 'NVARCHAR',
       name: 'NVarChar',
       hasCollation: true,
       dataLengthLength: 2,
       maximumLength: 4000,
       declaration: [Function],
       writeParameterData: [Function],
       id: 231 },
    colName: 'RoomDescription',
    collation:
     { lcid: 1055,
       codepage: 'WINDOWS-1254',
       flags: 208,
       version: 0,
       sortId: 0 },
    precision: undefined,
    scale: undefined,
    dataLength: 500,
    tableName: undefined },
  { userType: 0,
    flags: 9,
    type:
     { type: 'NVARCHAR',
       name: 'NVarChar',
       hasCollation: true,
       dataLengthLength: 2,
       maximumLength: 4000,
       declaration: [Function],
       writeParameterData: [Function],
       id: 231 },
    colName: 'Caption',
    collation:
     { lcid: 1055,
       codepage: 'WINDOWS-1254',
       flags: 208,
       version: 0,
       sortId: 0 },
    precision: undefined,
    scale: undefined,
    dataLength: 300,
    tableName: undefined },
  { userType: 0,
    flags: 9,
    type:
     { type: 'NVARCHAR',
       name: 'NVarChar',
       hasCollation: true,
       dataLengthLength: 2,
       maximumLength: 4000,
       declaration: [Function],
       writeParameterData: [Function],
       id: 231 },
    colName: 'ImageUrl',
    collation:
     { lcid: 1055,
       codepage: 'WINDOWS-1254',
       flags: 208,
       version: 0,
       sortId: 0 },
    precision: undefined,
    scale: undefined,
    dataLength: 1000,
    tableName: undefined },
  { userType: 0,
    flags: 9,
    type:
     { type: 'BIGVARCHR',
       name: 'VarChar',
       hasCollation: true,
       dataLengthLength: 2,
       maximumLength: 8000,
       declaration: [Function],
       writeParameterData: [Function],
       id: 167 },
    colName: 'Supplier',
    collation:
     { lcid: 1055,
       codepage: 'WINDOWS-1254',
       flags: 208,
       version: 0,
       sortId: 0 },
    precision: undefined,
    scale: undefined,
    dataLength: 50,
    tableName: undefined },
  { userType: 0,
    flags: 9,
    type: { type: 'INTN', name: 'IntN', dataLengthLength: 1, id: 38 },
    colName: 'RoomID',
    collation: undefined,
    precision: undefined,
    scale: undefined,
    dataLength: 4,
    tableName: undefined },
  { userType: 0,
    flags: 9,
    type:
     { type: 'NCHAR',
       name: 'NChar',
       hasCollation: true,
       dataLengthLength: 2,
       id: 239 },
    colName: 'PicDef',
    collation:
     { lcid: 1055,
       codepage: 'WINDOWS-1254',
       flags: 208,
       version: 0,
       sortId: 0 },
    precision: undefined,
    scale: undefined,
    dataLength: 2,
    tableName: undefined },
  { userType: 0,
    flags: 9,
    type:
     { type: 'NCHAR',
       name: 'NChar',
       hasCollation: true,
       dataLengthLength: 2,
       id: 239 },
    colName: 'PicType',
    collation:
     { lcid: 1055,
       codepage: 'WINDOWS-1254',
       flags: 208,
       version: 0,
       sortId: 0 },
    precision: undefined,
    scale: undefined,
    dataLength: 2,
    tableName: undefined },
  { userType: 0,
    flags: 9,
    type:
     { type: 'NVARCHAR',
       name: 'NVarChar',
       hasCollation: true,
       dataLengthLength: 2,
       maximumLength: 4000,
       declaration: [Function],
       writeParameterData: [Function],
       id: 231 },
    colName: 'Active',
    collation:
     { lcid: 1055,
       codepage: 'WINDOWS-1254',
       flags: 208,
       version: 0,
       sortId: 0 },
    precision: undefined,
    scale: undefined,
    dataLength: 20,
    tableName: undefined },
  RefID: { userType: 0,
    flags: 16,
    type:
     { type: 'INT4',
       name: 'Int',
       declaration: [Function],
       writeParameterData: [Function],
       id: 56 },
    colName: 'RefID',
    collation: undefined,
    precision: undefined,
    scale: undefined,
    dataLength: undefined,
    tableName: undefined },
  HotelID: { userType: 0,
    flags: 9,
    type: { type: 'INTN', name: 'IntN', dataLengthLength: 1, id: 38 },
    colName: 'HotelID',
    collation: undefined,
    precision: undefined,
    scale: undefined,
    dataLength: 4,
    tableName: undefined },
  RoomDescription: { userType: 0,
    flags: 9,
    type:
     { type: 'NVARCHAR',
       name: 'NVarChar',
       hasCollation: true,
       dataLengthLength: 2,
       maximumLength: 4000,
       declaration: [Function],
       writeParameterData: [Function],
       id: 231 },
    colName: 'RoomDescription',
    collation:
     { lcid: 1055,
       codepage: 'WINDOWS-1254',
       flags: 208,
       version: 0,
       sortId: 0 },
    precision: undefined,
    scale: undefined,
    dataLength: 500,
    tableName: undefined },
  Caption: { userType: 0,
    flags: 9,
    type:
     { type: 'NVARCHAR',
       name: 'NVarChar',
       hasCollation: true,
       dataLengthLength: 2,
       maximumLength: 4000,
       declaration: [Function],
       writeParameterData: [Function],
       id: 231 },
    colName: 'Caption',
    collation:
     { lcid: 1055,
       codepage: 'WINDOWS-1254',
       flags: 208,
       version: 0,
       sortId: 0 },
    precision: undefined,
    scale: undefined,
    dataLength: 300,
    tableName: undefined },
  ImageUrl: { userType: 0,
    flags: 9,
    type:
     { type: 'NVARCHAR',
       name: 'NVarChar',
       hasCollation: true,
       dataLengthLength: 2,
       maximumLength: 4000,
       declaration: [Function],
       writeParameterData: [Function],
       id: 231 },
    colName: 'ImageUrl',
    collation:
     { lcid: 1055,
       codepage: 'WINDOWS-1254',
       flags: 208,
       version: 0,
       sortId: 0 },
    precision: undefined,
    scale: undefined,
    dataLength: 1000,
    tableName: undefined },
  Supplier: { userType: 0,
    flags: 9,
    type:
     { type: 'BIGVARCHR',
       name: 'VarChar',
       hasCollation: true,
       dataLengthLength: 2,
       maximumLength: 8000,
       declaration: [Function],
       writeParameterData: [Function],
       id: 167 },
    colName: 'Supplier',
    collation:
     { lcid: 1055,
       codepage: 'WINDOWS-1254',
       flags: 208,
       version: 0,
       sortId: 0 },
    precision: undefined,
    scale: undefined,
    dataLength: 50,
    tableName: undefined },
  RoomID: { userType: 0,
    flags: 9,
    type: { type: 'INTN', name: 'IntN', dataLengthLength: 1, id: 38 },
    colName: 'RoomID',
    collation: undefined,
    precision: undefined,
    scale: undefined,
    dataLength: 4,
    tableName: undefined },
  PicDef: { userType: 0,
    flags: 9,
    type:
     { type: 'NCHAR',
       name: 'NChar',
       hasCollation: true,
       dataLengthLength: 2,
       id: 239 },
    colName: 'PicDef',
    collation:
     { lcid: 1055,
       codepage: 'WINDOWS-1254',
       flags: 208,
       version: 0,
       sortId: 0 },
    precision: undefined,
    scale: undefined,
    dataLength: 2,
    tableName: undefined },
  PicType: { userType: 0,
    flags: 9,
    type:
     { type: 'NCHAR',
       name: 'NChar',
       hasCollation: true,
       dataLengthLength: 2,
       id: 239 },
    colName: 'PicType',
    collation:
     { lcid: 1055,
       codepage: 'WINDOWS-1254',
       flags: 208,
       version: 0,
       sortId: 0 },
    precision: undefined,
    scale: undefined,
    dataLength: 2,
    tableName: undefined },
  Active: { userType: 0,
    flags: 9,
    type:
     { type: 'NVARCHAR',
       name: 'NVarChar',
       hasCollation: true,
       dataLengthLength: 2,
       maximumLength: 4000,
       declaration: [Function],
       writeParameterData: [Function],
       id: 231 },
    colName: 'Active',
    collation:
     { lcid: 1055,
       codepage: 'WINDOWS-1254',
       flags: 208,
       version: 0,
       sortId: 0 },
    precision: undefined,
    scale: undefined,
    dataLength: 20,
    tableName: undefined } ]
/*
0
1
2
3
4
5
6
7
8
9
RefID
HotelID
RoomDescription
Caption
ImageUrl
Supplier
RoomID
PicDef
PicType
Active
  */



var RoomDescription: { userType: 0,
  flags: 9,
  type:
   { type: 'NVARCHAR',
     name: 'NVarChar',
     hasCollation: true,
     dataLengthLength: 2,
     maximumLength: 4000,
     declaration: [Function],
     writeParameterData: [Function],
     id: 231 },
  colName: 'RoomDescription',
  collation:
   { lcid: 1055,
     codepage: 'WINDOWS-1254',
     flags: 208,
     version: 0,
     sortId: 0 },
  precision: undefined,
  scale: undefined,
  dataLength: 500,
  tableName: undefined }