module.exports = {
  'Bit': 'Boolean',
  'TinyInt': 'Numeric',
  'SmallInt': 'Numeric',
  'Int': 'Numeric',
  'BigInt': 'Numeric',
  'Numeric': 'Numeric',
  'Decimal': 'Numeric',
  'SmallMoney': 'Numeric',
  'Money': 'Numeric',
  'Float': 'Numeric',
  'real': 'Numeric',
  'SmallDateTime': 'Date',
  'DateTime': 'Date',
  'Char': 'String',
  'VarChar': 'String',
  'Text': 'String',
  'NChar': 'String',
  'NVarChar': 'String',
  'NText': 'String',
  'Binary': '[Numeric]',
  'VarBinary': '[Numeric]',
  'Image': '[Numeric]',
  'Null': 'null',
  'UniqueIdentifier': '[Numeric]',
  'xml': 'String'
};