module.exports = {
  "TinyInt":          "Number",
  "Bit":              "Boolean",
  "SmallInt":         "Number",
  "Int":              "Number",
  "SmallDateTime":    "Date",
  "Real":             "Number",
  "Money":            "Number",
  "DateTime":         "Date",
  "Float":            "Number",
  "SmallMoney":       "Number",
  "BigInt":           "Number",
  "Image":            "Array",
  "Text":             "String",
  "UniqueIdentifierN":"Array",
  "IntN":             "Number",
  "NText":            "String",
  "BitN":             "Boolean",
  "DecimalN":         "Number",
  "NumberN":          "Number",
  "FloatN":           "Number",
  "MoneyN":           "Number",
  "DateTimeN":        "Date",
  "VarBinary":        "Array",
  "VarChar":          "String",
  "Binary":           "Array",
  "Char":             "String",
  "NVarChar":         "String",
  "NChar":            "String",
  "Xml":              "String"
};
/*
module.exports = {
  "Null":             "null",
  "TinyInt":          "Numeric",
  "Bit":              "Boolean",
  "SmallInt":         "Numeric",
  "Int":              "Numeric",
  "SmallDateTime":    "Date",
  "Real":             "Numeric",
  "Money":            "Numeric",
  "DateTime":         "Date",
  "Float":            "Numeric",
  "SmallMoney":       "Numeric",
  "BigInt":           "Numeric",
  "Image":            "[Numeric]",
  "Text":             "String",
  "UniqueIdentifierN":"[Numeric]",
  "IntN":             "Numeric",
  "NText":            "String",
  "BitN":             "Boolean",
  "DecimalN":         "Numeric",
  "NumericN":         "Numeric",
  "FloatN":           "Numeric",
  "MoneyN":           "Numeric",
  "DateTimeN":        "Date",
  "VarBinary":        "[Numeric]",
  "VarChar":          "String",
  "Binary":           "[Numeric]",
  "Char":             "String",
  "NVarChar":         "String",
  "NChar":            "String",
  "Xml":              "String"
};
*/